version: "3.9"
services:
  postgres:
    container_name: bank-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Mardali -d bank"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
