spring:
  application:
    name: BankCardsApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: bank
    password: bank
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/changelog.yaml
    default-schema: public

  doc:
    swagger-ui:
      path: /swagger-ui.html
      tagsSorter: alpha
      operationsSorter: alpha
    api-docs:
      path: /api-docs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

# JWT Configuration
app:
  jwt:
    secret: your-secret-key-here-make-it-long-and-secure-for-production
    expiration: 86400000 # 24 hours in milliseconds
